services:
  zooapi.web:
    image: zooapi.web
    build:
      context: .
      dockerfile: ZooApi.Web/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=zoo_db;Username=zoo_user;Password=zoo_pass
    depends_on:
      - postgres
      
  postgres:
    image: postgres:17
    container_name: zoo_postgres
    environment:
      POSTGRES_DB: zoo_db
      POSTGRES_USER: zoo_user
      POSTGRES_PASSWORD: zoo_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: zoo_rabbit
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  
volumes:
  postgres_data: