services:
  zooapi.web:
    image: zooapi.web
    build:
      context: .
      dockerfile: ZooApi.Web/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=zoo_db;Username=zoo_user;Password=zoo_pass
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__Redis=redis:6379
      - MailSettings__Host=mailhog
      - MailSettings__Port=1025
      - MailSettings__Username=test@test.com
      - MailSettings__Password=
    depends_on:
      - postgres
      - rabbitmq
      - redis
      
  postgres:
    image: postgres:17
    container_name: zoo_postgres
    environment:
      POSTGRES_DB: zoo_db
      POSTGRES_USER: zoo_user
      POSTGRES_PASSWORD: zoo_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  rabbitmq:
    image: rabbitmq:4-management
    container_name: zoo_rabbit
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      
  redis:
    image: redis:alpine
    container_name: zoo_redis
    ports:
      - "6379:6379"
  
  mailhog:
    image: mailhog/mailhog
    container_name: zoo_mailhog
    ports:
      - "1025:1025"
      - "8025:8025" 

volumes:
  postgres_data: